name: Enter SSH

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Optional message for the run'
        required: false
        default: 'Manual run'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
